import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";

import "./globals.css";

import Header from "@/components/site-header";
import Footer from "@/components/footer";

const bodyFont = Montserrat({
  subsets: ['latin'],
  variable: '--font-primary',
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-white font-sans antialiased", bodyFont.variable)}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
